name: Link Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose --accept 200,206,429,503 --exclude-mail '#'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
